## Font configuration ---------------------------------------

[font]
size = 9

## When true, Alacritty will use a custom built-in font for box drawing characters and powerline symbols.
builtin_box_drawing = true

[font.normal]
family = "MartianMono Nerd Font"
style = "Medium"

[font.bold]
family = "MartianMono Nerd Font"
style = "Bold"

[font.italic]
family = "MartianMono Nerd Font"

[font.bold_italic]
family = "MartianMono Nerd Font"

[font.offset]
x = -1
y = 5

## Glyph offset determines the locations of the glyphs within their cells with the default being at the bottom.
## Increasing 'x' moves the glyph to the right, increasing 'y' moves the glyph upward.
[font.glyph_offset]
x = 0
y = 0

## worthy used fonts
## 'Monocraft' SemiBold: offset x=1, y=5
## 'MartianMono Nerd Font' Medium: offset x=-1, y=5
